# Generated by Django 2.2.13 on 2020-08-12 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yazı',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi', models.TextField()),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
